(()=>{
'use strict';
const KEY='khatavar_practice_history_v1';
const fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const $=s=>document.querySelector(s);
let state={text:'',typed:'',started:0,elapsed:0,running:false,finished:false,errors:0,lastError:false};
let timer=null;
function readHistory(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}
function writeHistory(h){localStorage.setItem(KEY,JSON.stringify(h.slice(-30)))}
function style(){if($('#practiceStyles'))return;const s=document.createElement('style');s.id='practiceStyles';s.textContent=`#practiceBtn{white-space:nowrap}.practice-backdrop{position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.58);display:grid;place-items:center;padding:20px}.practice-modal{width:min(900px,96vw);max-height:92vh;overflow:auto;padding:24px;border:1px solid rgba(255,255,255,.14);border-radius:24px}.practice-grid{display:grid;grid-template-columns:1fr 280px;gap:18px}.practice-card{padding:18px;border-radius:18px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.09)}.practice-target{font-size:26px;line-height:2.1;min-height:170px;white-space:pre-wrap;direction:rtl;user-select:none}.practice-target .ok{opacity:.58}.practice-target .bad{text-decoration:underline;text-decoration-thickness:2px}.practice-target .current{outline:2px solid currentColor;border-radius:4px}.practice-input{width:100%;min-height:150px;resize:vertical;font:inherit;font-size:22px;line-height:2;padding:14px;border-radius:14px}.practice-stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}.practice-stat{padding:12px;border-radius:14px;background:rgba(255,255,255,.05)}.practice-stat b{display:block;font-size:24px;margin-top:4px}.practice-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.practice-actions button{padding:9px 14px;border-radius:10px}.practice-result{padding:14px;border-radius:14px;margin-top:14px;background:rgba(255,255,255,.06)}.practice-close{position:absolute;top:12px;left:12px;z-index:2;width:38px;height:38px;display:grid;place-items:center;margin:0;padding:0!important;float:none;font-size:24px;line-height:1;border:1px solid rgba(255,255,255,.14)!important;border-radius:10px!important;background:rgba(255,255,255,.06)!important;color:inherit;cursor:pointer;pointer-events:auto}.practice-close:hover{background:rgba(255,255,255,.12)!important}.practice-history{max-height:190px;overflow:auto;font-size:13px;line-height:1.9}@media(max-width:760px){.practice-grid{grid-template-columns:1fr}.practice-target{font-size:21px}}`;document.head.appendChild(s)}
function sourceText(){const t=$('#textInput')?.value?.trim();return t||'خط‌آور؛ تمرین تایپ فارسی با دقت، سرعت و نیم‌فاصله. امروز یک متن کوتاه را آرام و دقیق تایپ کنید.'}
function open(){style();const existing=$('#practiceModal');if(existing){existing.hidden=false;existing.removeAttribute('aria-hidden');reset();return}const b=document.createElement('div');b.id='practiceModal';b.className='practice-backdrop';b.innerHTML=`<div class="practice-modal glass"><button type="button" class="practice-close" id="practiceClose" aria-label="بستن تمرین" title="بستن">×</button><h2>تمرین تایپ</h2><p>سرعت را دنبال نکن؛ اول دقت، بعد سرعت. متن فارسی را دقیقاً همان‌طور که نمایش داده شده تایپ کن.</p><div class="practice-grid"><div><div class="practice-card"><div class="section-caption">متن تمرین</div><div id="practiceTarget" class="practice-target"></div></div><div class="practice-card" style="margin-top:14px"><div class="section-caption">تایپ شما</div><textarea id="practiceInput" class="practice-input" dir="rtl" autocomplete="off" autocorrect="off" spellcheck="false" placeholder="از اینجا شروع کن..."></textarea><div class="practice-actions"><button id="practiceStart" class="accent">شروع دوباره</button><button id="practiceUseEditor">استفاده از متن فعلی</button><button id="practiceNewSample">نمونه جدید</button></div><div id="practiceResult" class="practice-result" hidden></div></div></div><aside><div class="practice-card"><div class="section-caption">آمار زنده</div><div class="practice-stats"><div class="practice-stat">زمان<b id="practiceTime">۰:۰۰</b></div><div class="practice-stat">دقت<b id="practiceAccuracy">۱۰۰٪</b></div><div class="practice-stat">CPM<b id="practiceCpm">۰</b></div><div class="practice-stat">خطا<b id="practiceErrors">۰</b></div></div></div><div class="practice-card" style="margin-top:14px"><div class="section-caption">سوابق اخیر</div><div id="practiceHistory" class="practice-history"></div></div></aside></div></div>`;document.body.appendChild(b);const closeButton=$('#practiceClose');closeButton.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();close()},{capture:true});closeButton.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();close()},{capture:true});$('#practiceStart').onclick=reset;$('#practiceUseEditor').onclick=()=>{state.text=sourceText();reset(false)};$('#practiceNewSample').onclick=()=>{state.text='در تایپوگرافی فارسی، فاصله‌ها، نیم‌فاصله‌ها و شکل درست حروف اهمیت زیادی دارند. تمرین منظم باعث می‌شود دقت و سرعت تایپ بهتر شود.';reset(false)};$('#practiceInput').addEventListener('input',onInput);b.addEventListener('pointerdown',e=>{if(e.target===b)close()});state.text=sourceText();render();}
function close(){stop();const m=$('#practiceModal');if(!m)return;m.hidden=true;m.setAttribute('aria-hidden','true');m.remove();setTimeout(()=>{const input=$('#textInput');if(input&&document.activeElement!==input)input.focus() },0)}
function reset(loadSource=true){stop();state={text:loadSource?sourceText():(state.text||sourceText()),typed:'',started:0,elapsed:0,running:false,finished:false,errors:0,lastError:false};render();setTimeout(()=>$('#practiceInput')?.focus(),40)}
function start(){if(state.running)return;state.running=true;state.finished=false;state.started=performance.now()-state.elapsed*1000;timer=setInterval(updateStats,250);updateStats()}
function stop(){if(timer){clearInterval(timer);timer=null}state.running=false}
function onInput(e){state.typed=e.target.value;if(!state.typed){stop();state.started=0;state.elapsed=0;state.errors=0;render();return}if(!state.running)start();state.errors=0;for(let i=0;i<state.typed.length;i++)if(state.typed[i]!==state.text[i])state.errors++;if(state.typed.length>=state.text.length){state.typed=state.typed.slice(0,state.text.length);e.target.value=state.typed;finish()}renderTarget();updateStats()}
function finish(){state.finished=true;stop();state.elapsed=state.started?Math.max(.1,(performance.now()-state.started)/1000):0;const chars=state.text.length;const correct=Math.max(0,chars-state.errors);const accuracy=chars?correct/chars:1;const cpm=Math.round(correct/(state.elapsed/60));const h=readHistory();h.push({date:new Date().toISOString(),seconds:Math.round(state.elapsed),accuracy:Math.round(accuracy*100),cpm,errors:state.errors,chars});writeHistory(h);const r=$('#practiceResult');if(r){r.hidden=false;r.textContent=`تمام شد 🎉  دقت: ${fa(Math.round(accuracy*100))}٪ · سرعت: ${fa(cpm)} CPM · خطا: ${fa(state.errors)}`;}}
function updateStats(){if(state.running)state.elapsed=Math.max(0,(performance.now()-state.started)/1000);const chars=state.typed.length;let correct=0;for(let i=0;i<chars;i++)if(state.typed[i]===state.text[i])correct++;const accuracy=chars?correct/chars:1;const cpm=state.elapsed>0?Math.round(correct/(state.elapsed/60)):0;const min=Math.floor(state.elapsed/60),sec=Math.floor(state.elapsed%60);if($('#practiceTime'))$('#practiceTime').textContent=`${fa(min)}:${String(sec).padStart(2,'0').replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d])}`;if($('#practiceAccuracy'))$('#practiceAccuracy').textContent=fa(Math.round(accuracy*100))+'٪';if($('#practiceCpm'))$('#practiceCpm').textContent=fa(cpm);if($('#practiceErrors'))$('#practiceErrors').textContent=fa(state.errors);renderTarget();}
function renderTarget(){const el=$('#practiceTarget');if(!el)return;let html='';for(let i=0;i<state.text.length;i++){const ch=state.text[i];const cls=i<state.typed.length?(state.typed[i]===ch?'ok':'bad'):(i===state.typed.length?'current':'');html+=`<span class="${cls}">${ch===' ' ? ' ' : ch}</span>`}el.innerHTML=html;renderHistory()}
function renderHistory(){const el=$('#practiceHistory');if(!el)return;const h=readHistory().slice().reverse();el.innerHTML=h.length?h.map(x=>`<div>• ${fa(x.cpm)} CPM · ${fa(x.accuracy)}٪ دقت · ${fa(x.errors)} خطا</div>`).join(''):'هنوز رکوردی ثبت نشده.'}
function mountButton(){style();const existing=$('#practiceBtn');if(existing){if(existing.dataset.practiceBound==='1')return;existing.dataset.practiceBound='1';existing.onclick=open;return}const host=document.querySelector('.top-actions');if(!host)return;const b=document.createElement('button');b.id='practiceBtn';b.textContent='⌨ تمرین';b.title='حالت تمرین تایپ';b.dataset.practiceBound='1';b.onclick=open;host.insertBefore(b,host.querySelector('#exportBtn')||null)}
new MutationObserver(mountButton).observe(document.body,{childList:true,subtree:true});mountButton();window.KhatAvarPractice={open,reset};
})();